// <auto-generated />
namespace MyAcademy_MVC_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class makeUiCompleteDynamic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makeUiCompleteDynamic));
        
        string IMigrationMetadata.Id
        {
            get { return "202601112131476_makeUiCompleteDynamic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
